<?php

namespace App\Services;

use App\Models\JournalEntry;
use App\Models\Product;
use App\Models\Sale;
use Illuminate\Support\Str;
use InvalidArgumentException;

class AccountingService
{
    /**
     * Record opening inventory against capital.
     */
    public function recordOpeningInventory(Product $product): void
    {
        $openingValue = $this->money((float) $product->purchase_price * (int) $product->stock);

        if ($openingValue <= 0) {
            return;
        }

        $this->createDoubleEntry(
            debitAccount: $this->account('inventory'),
            creditAccount: $this->account('capital'),
            amount: $openingValue,
            referenceType: Product::class,
            referenceId: $product->id,
            date: ($product->created_at ?? now())->toDateString(),
        );
    }

    /**
     * Record all accounting transactions generated by a sale.
     */
    public function recordSale(Sale $sale, float $cogsAmount): void
    {
        $date = $sale->date->toDateString();
        $referenceType = Sale::class;
        $referenceId = $sale->id;

        $totalReceivable = $this->money((float) $sale->total_amount);
        $netSale = $this->money((float) $sale->subtotal - (float) $sale->discount);
        $vatAmount = $this->money((float) $sale->vat_amount);
        $paidAmount = $this->money((float) $sale->paid_amount);
        $cogs = $this->money($cogsAmount);

        // A) Revenue Entry: Dr Accounts Receivable, Cr Sales Revenue, Cr VAT Payable
        $this->createEntry(
            accountName: $this->account('accounts_receivable'),
            debit: $totalReceivable,
            credit: null,
            referenceType: $referenceType,
            referenceId: $referenceId,
            date: $date,
        );

        $this->createEntry(
            accountName: $this->account('sales_revenue'),
            debit: null,
            credit: $netSale,
            referenceType: $referenceType,
            referenceId: $referenceId,
            date: $date,
        );

        $this->createEntry(
            accountName: $this->account('vat_payable'),
            debit: null,
            credit: $vatAmount,
            referenceType: $referenceType,
            referenceId: $referenceId,
            date: $date,
        );

        // B) COGS Entry: Dr Cost of Goods Sold, Cr Inventory
        $this->createDoubleEntry(
            debitAccount: $this->account('cost_of_goods_sold'),
            creditAccount: $this->account('inventory'),
            amount: $cogs,
            referenceType: $referenceType,
            referenceId: $referenceId,
            date: $date,
        );

        // C) Payment Entry: Dr Cash, Cr Accounts Receivable
        $this->createDoubleEntry(
            debitAccount: $this->account('cash'),
            creditAccount: $this->account('accounts_receivable'),
            amount: $paidAmount,
            referenceType: $referenceType,
            referenceId: $referenceId,
            date: $date,
        );
    }

    /**
     * Create a balanced debit/credit pair.
     */
    private function createDoubleEntry(
        string $debitAccount,
        string $creditAccount,
        float $amount,
        string $referenceType,
        int $referenceId,
        string $date,
    ): void {
        $amount = $this->money($amount);

        if ($amount <= 0) {
            return;
        }

        $this->createEntry(
            accountName: $debitAccount,
            debit: $amount,
            credit: null,
            referenceType: $referenceType,
            referenceId: $referenceId,
            date: $date,
        );

        $this->createEntry(
            accountName: $creditAccount,
            debit: null,
            credit: $amount,
            referenceType: $referenceType,
            referenceId: $referenceId,
            date: $date,
        );
    }

    /**
     * Persist a single journal line.
     */
    private function createEntry(
        string $accountName,
        ?float $debit,
        ?float $credit,
        string $referenceType,
        int $referenceId,
        string $date,
    ): void {
        $debit = $debit !== null ? $this->money($debit) : null;
        $credit = $credit !== null ? $this->money($credit) : null;

        if (($debit ?? 0) <= 0 && ($credit ?? 0) <= 0) {
            return;
        }

        if (($debit ?? 0) > 0 && ($credit ?? 0) > 0) {
            throw new InvalidArgumentException('A journal entry line cannot contain both debit and credit.');
        }

        JournalEntry::query()->create([
            'date' => $date,
            'account_name' => $accountName,
            'debit' => $debit,
            'credit' => $credit,
            'reference_type' => $referenceType,
            'reference_id' => $referenceId,
        ]);
    }

    /**
     * Resolve account labels from configuration.
     */
    private function account(string $key): string
    {
        return (string) config(
            "accounting.accounts.{$key}",
            Str::of($key)->replace('_', ' ')->title()->toString()
        );
    }

    /**
     * Normalize money precision.
     */
    private function money(float $amount): float
    {
        return round($amount, 2);
    }
}
